// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v5.29.3
// source: gateway/code_manage.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "code_manage.v1";

export enum Language {
  LANGUAGE_UNSPECIFIED = 0,
  JAVASCRIPT = 1,
  PYTHON = 2,
  GO = 3,
  UNRECOGNIZED = -1,
}

export function languageFromJSON(object: any): Language {
  switch (object) {
    case 0:
    case "LANGUAGE_UNSPECIFIED":
      return Language.LANGUAGE_UNSPECIFIED;
    case 1:
    case "JAVASCRIPT":
      return Language.JAVASCRIPT;
    case 2:
    case "PYTHON":
      return Language.PYTHON;
    case 3:
    case "GO":
      return Language.GO;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Language.UNRECOGNIZED;
  }
}

export function languageToJSON(object: Language): string {
  switch (object) {
    case Language.LANGUAGE_UNSPECIFIED:
      return "LANGUAGE_UNSPECIFIED";
    case Language.JAVASCRIPT:
      return "JAVASCRIPT";
    case Language.PYTHON:
      return "PYTHON";
    case Language.GO:
      return "GO";
    case Language.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface TestCase {
  Id: string;
  input: string;
  output: string;
}

export interface SubmitCodeExecRequest {
  problemId: string;
  userId: string;
  username: string;
  country?: string | undefined;
  userCode: string;
  language: Language;
}

export interface SubmitCodeExecResponse {
  submissionId: string;
}

export interface RunCodeExecRequest {
  problemId: string;
  language: Language;
  userCode: string;
  testCases: TestCase[];
}

export interface RunCodeExecResponse {
  tempId: string;
}

export interface CustomCodeExecRequest {
  userCode: string;
  language: Language;
}

export interface CustomCodeExecResponse {
  tempId: string;
}

function createBaseTestCase(): TestCase {
  return { Id: "", input: "", output: "" };
}

export const TestCase: MessageFns<TestCase> = {
  encode(message: TestCase, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.Id !== "") {
      writer.uint32(10).string(message.Id);
    }
    if (message.input !== "") {
      writer.uint32(18).string(message.input);
    }
    if (message.output !== "") {
      writer.uint32(26).string(message.output);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TestCase {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTestCase();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.Id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.input = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.output = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TestCase {
    return {
      Id: isSet(object.Id) ? globalThis.String(object.Id) : "",
      input: isSet(object.input) ? globalThis.String(object.input) : "",
      output: isSet(object.output) ? globalThis.String(object.output) : "",
    };
  },

  toJSON(message: TestCase): unknown {
    const obj: any = {};
    if (message.Id !== "") {
      obj.Id = message.Id;
    }
    if (message.input !== "") {
      obj.input = message.input;
    }
    if (message.output !== "") {
      obj.output = message.output;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TestCase>, I>>(base?: I): TestCase {
    return TestCase.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TestCase>, I>>(object: I): TestCase {
    const message = createBaseTestCase();
    message.Id = object.Id ?? "";
    message.input = object.input ?? "";
    message.output = object.output ?? "";
    return message;
  },
};

function createBaseSubmitCodeExecRequest(): SubmitCodeExecRequest {
  return { problemId: "", userId: "", username: "", country: undefined, userCode: "", language: 0 };
}

export const SubmitCodeExecRequest: MessageFns<SubmitCodeExecRequest> = {
  encode(message: SubmitCodeExecRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.problemId !== "") {
      writer.uint32(10).string(message.problemId);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    if (message.username !== "") {
      writer.uint32(26).string(message.username);
    }
    if (message.country !== undefined) {
      writer.uint32(34).string(message.country);
    }
    if (message.userCode !== "") {
      writer.uint32(42).string(message.userCode);
    }
    if (message.language !== 0) {
      writer.uint32(48).int32(message.language);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SubmitCodeExecRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubmitCodeExecRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.problemId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.country = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.userCode = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.language = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SubmitCodeExecRequest {
    return {
      problemId: isSet(object.problemId) ? globalThis.String(object.problemId) : "",
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      username: isSet(object.username) ? globalThis.String(object.username) : "",
      country: isSet(object.country) ? globalThis.String(object.country) : undefined,
      userCode: isSet(object.userCode) ? globalThis.String(object.userCode) : "",
      language: isSet(object.language) ? languageFromJSON(object.language) : 0,
    };
  },

  toJSON(message: SubmitCodeExecRequest): unknown {
    const obj: any = {};
    if (message.problemId !== "") {
      obj.problemId = message.problemId;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.username !== "") {
      obj.username = message.username;
    }
    if (message.country !== undefined) {
      obj.country = message.country;
    }
    if (message.userCode !== "") {
      obj.userCode = message.userCode;
    }
    if (message.language !== 0) {
      obj.language = languageToJSON(message.language);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SubmitCodeExecRequest>, I>>(base?: I): SubmitCodeExecRequest {
    return SubmitCodeExecRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SubmitCodeExecRequest>, I>>(object: I): SubmitCodeExecRequest {
    const message = createBaseSubmitCodeExecRequest();
    message.problemId = object.problemId ?? "";
    message.userId = object.userId ?? "";
    message.username = object.username ?? "";
    message.country = object.country ?? undefined;
    message.userCode = object.userCode ?? "";
    message.language = object.language ?? 0;
    return message;
  },
};

function createBaseSubmitCodeExecResponse(): SubmitCodeExecResponse {
  return { submissionId: "" };
}

export const SubmitCodeExecResponse: MessageFns<SubmitCodeExecResponse> = {
  encode(message: SubmitCodeExecResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.submissionId !== "") {
      writer.uint32(10).string(message.submissionId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SubmitCodeExecResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubmitCodeExecResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.submissionId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SubmitCodeExecResponse {
    return { submissionId: isSet(object.submissionId) ? globalThis.String(object.submissionId) : "" };
  },

  toJSON(message: SubmitCodeExecResponse): unknown {
    const obj: any = {};
    if (message.submissionId !== "") {
      obj.submissionId = message.submissionId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SubmitCodeExecResponse>, I>>(base?: I): SubmitCodeExecResponse {
    return SubmitCodeExecResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SubmitCodeExecResponse>, I>>(object: I): SubmitCodeExecResponse {
    const message = createBaseSubmitCodeExecResponse();
    message.submissionId = object.submissionId ?? "";
    return message;
  },
};

function createBaseRunCodeExecRequest(): RunCodeExecRequest {
  return { problemId: "", language: 0, userCode: "", testCases: [] };
}

export const RunCodeExecRequest: MessageFns<RunCodeExecRequest> = {
  encode(message: RunCodeExecRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.problemId !== "") {
      writer.uint32(10).string(message.problemId);
    }
    if (message.language !== 0) {
      writer.uint32(24).int32(message.language);
    }
    if (message.userCode !== "") {
      writer.uint32(34).string(message.userCode);
    }
    for (const v of message.testCases) {
      TestCase.encode(v!, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RunCodeExecRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRunCodeExecRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.problemId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.language = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.userCode = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.testCases.push(TestCase.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RunCodeExecRequest {
    return {
      problemId: isSet(object.problemId) ? globalThis.String(object.problemId) : "",
      language: isSet(object.language) ? languageFromJSON(object.language) : 0,
      userCode: isSet(object.userCode) ? globalThis.String(object.userCode) : "",
      testCases: globalThis.Array.isArray(object?.testCases)
        ? object.testCases.map((e: any) => TestCase.fromJSON(e))
        : [],
    };
  },

  toJSON(message: RunCodeExecRequest): unknown {
    const obj: any = {};
    if (message.problemId !== "") {
      obj.problemId = message.problemId;
    }
    if (message.language !== 0) {
      obj.language = languageToJSON(message.language);
    }
    if (message.userCode !== "") {
      obj.userCode = message.userCode;
    }
    if (message.testCases?.length) {
      obj.testCases = message.testCases.map((e) => TestCase.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RunCodeExecRequest>, I>>(base?: I): RunCodeExecRequest {
    return RunCodeExecRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RunCodeExecRequest>, I>>(object: I): RunCodeExecRequest {
    const message = createBaseRunCodeExecRequest();
    message.problemId = object.problemId ?? "";
    message.language = object.language ?? 0;
    message.userCode = object.userCode ?? "";
    message.testCases = object.testCases?.map((e) => TestCase.fromPartial(e)) || [];
    return message;
  },
};

function createBaseRunCodeExecResponse(): RunCodeExecResponse {
  return { tempId: "" };
}

export const RunCodeExecResponse: MessageFns<RunCodeExecResponse> = {
  encode(message: RunCodeExecResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tempId !== "") {
      writer.uint32(10).string(message.tempId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RunCodeExecResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRunCodeExecResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tempId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RunCodeExecResponse {
    return { tempId: isSet(object.tempId) ? globalThis.String(object.tempId) : "" };
  },

  toJSON(message: RunCodeExecResponse): unknown {
    const obj: any = {};
    if (message.tempId !== "") {
      obj.tempId = message.tempId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RunCodeExecResponse>, I>>(base?: I): RunCodeExecResponse {
    return RunCodeExecResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RunCodeExecResponse>, I>>(object: I): RunCodeExecResponse {
    const message = createBaseRunCodeExecResponse();
    message.tempId = object.tempId ?? "";
    return message;
  },
};

function createBaseCustomCodeExecRequest(): CustomCodeExecRequest {
  return { userCode: "", language: 0 };
}

export const CustomCodeExecRequest: MessageFns<CustomCodeExecRequest> = {
  encode(message: CustomCodeExecRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userCode !== "") {
      writer.uint32(18).string(message.userCode);
    }
    if (message.language !== 0) {
      writer.uint32(24).int32(message.language);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CustomCodeExecRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCustomCodeExecRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userCode = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.language = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CustomCodeExecRequest {
    return {
      userCode: isSet(object.userCode) ? globalThis.String(object.userCode) : "",
      language: isSet(object.language) ? languageFromJSON(object.language) : 0,
    };
  },

  toJSON(message: CustomCodeExecRequest): unknown {
    const obj: any = {};
    if (message.userCode !== "") {
      obj.userCode = message.userCode;
    }
    if (message.language !== 0) {
      obj.language = languageToJSON(message.language);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CustomCodeExecRequest>, I>>(base?: I): CustomCodeExecRequest {
    return CustomCodeExecRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CustomCodeExecRequest>, I>>(object: I): CustomCodeExecRequest {
    const message = createBaseCustomCodeExecRequest();
    message.userCode = object.userCode ?? "";
    message.language = object.language ?? 0;
    return message;
  },
};

function createBaseCustomCodeExecResponse(): CustomCodeExecResponse {
  return { tempId: "" };
}

export const CustomCodeExecResponse: MessageFns<CustomCodeExecResponse> = {
  encode(message: CustomCodeExecResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tempId !== "") {
      writer.uint32(10).string(message.tempId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CustomCodeExecResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCustomCodeExecResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tempId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CustomCodeExecResponse {
    return { tempId: isSet(object.tempId) ? globalThis.String(object.tempId) : "" };
  },

  toJSON(message: CustomCodeExecResponse): unknown {
    const obj: any = {};
    if (message.tempId !== "") {
      obj.tempId = message.tempId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CustomCodeExecResponse>, I>>(base?: I): CustomCodeExecResponse {
    return CustomCodeExecResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CustomCodeExecResponse>, I>>(object: I): CustomCodeExecResponse {
    const message = createBaseCustomCodeExecResponse();
    message.tempId = object.tempId ?? "";
    return message;
  },
};

export type CodeManageServiceService = typeof CodeManageServiceService;
export const CodeManageServiceService = {
  submitCodeExec: {
    path: "/code_manage.v1.CodeManageService/SubmitCodeExec",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: SubmitCodeExecRequest): Buffer =>
      Buffer.from(SubmitCodeExecRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): SubmitCodeExecRequest => SubmitCodeExecRequest.decode(value),
    responseSerialize: (value: SubmitCodeExecResponse): Buffer =>
      Buffer.from(SubmitCodeExecResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): SubmitCodeExecResponse => SubmitCodeExecResponse.decode(value),
  },
  runCodeExec: {
    path: "/code_manage.v1.CodeManageService/RunCodeExec",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: RunCodeExecRequest): Buffer => Buffer.from(RunCodeExecRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): RunCodeExecRequest => RunCodeExecRequest.decode(value),
    responseSerialize: (value: RunCodeExecResponse): Buffer => Buffer.from(RunCodeExecResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): RunCodeExecResponse => RunCodeExecResponse.decode(value),
  },
  customCodeExec: {
    path: "/code_manage.v1.CodeManageService/CustomCodeExec",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: CustomCodeExecRequest): Buffer =>
      Buffer.from(CustomCodeExecRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CustomCodeExecRequest => CustomCodeExecRequest.decode(value),
    responseSerialize: (value: CustomCodeExecResponse): Buffer =>
      Buffer.from(CustomCodeExecResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CustomCodeExecResponse => CustomCodeExecResponse.decode(value),
  },
} as const;

export interface CodeManageServiceServer extends UntypedServiceImplementation {
  submitCodeExec: handleUnaryCall<SubmitCodeExecRequest, SubmitCodeExecResponse>;
  runCodeExec: handleUnaryCall<RunCodeExecRequest, RunCodeExecResponse>;
  customCodeExec: handleUnaryCall<CustomCodeExecRequest, CustomCodeExecResponse>;
}

export interface CodeManageServiceClient extends Client {
  submitCodeExec(
    request: SubmitCodeExecRequest,
    callback: (error: ServiceError | null, response: SubmitCodeExecResponse) => void,
  ): ClientUnaryCall;
  submitCodeExec(
    request: SubmitCodeExecRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: SubmitCodeExecResponse) => void,
  ): ClientUnaryCall;
  submitCodeExec(
    request: SubmitCodeExecRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: SubmitCodeExecResponse) => void,
  ): ClientUnaryCall;
  runCodeExec(
    request: RunCodeExecRequest,
    callback: (error: ServiceError | null, response: RunCodeExecResponse) => void,
  ): ClientUnaryCall;
  runCodeExec(
    request: RunCodeExecRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: RunCodeExecResponse) => void,
  ): ClientUnaryCall;
  runCodeExec(
    request: RunCodeExecRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: RunCodeExecResponse) => void,
  ): ClientUnaryCall;
  customCodeExec(
    request: CustomCodeExecRequest,
    callback: (error: ServiceError | null, response: CustomCodeExecResponse) => void,
  ): ClientUnaryCall;
  customCodeExec(
    request: CustomCodeExecRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CustomCodeExecResponse) => void,
  ): ClientUnaryCall;
  customCodeExec(
    request: CustomCodeExecRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CustomCodeExecResponse) => void,
  ): ClientUnaryCall;
}

export const CodeManageServiceClient = makeGenericClientConstructor(
  CodeManageServiceService,
  "code_manage.v1.CodeManageService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): CodeManageServiceClient;
  service: typeof CodeManageServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
