// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v5.29.3
// source: gateway/collab.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { Empty } from "../google/protobuf/empty";

export const protobufPackage = "collab.v1";

export interface Session {
  Id: string;
  ownerId: string;
  participants: string[];
  createdAt: string;
  updatedAt: string;
  endedAt: string;
  status: string;
  language: string;
}

export interface CreateSessionRequest {
  ownerId: string;
}

export interface CreateSessionResponse {
  inviteToken: string;
}

export interface SessionStatus {
  active: number;
  ended: number;
  offline: number;
}

export interface GetSessionStatsResponse {
  total?: SessionStatus | undefined;
  today?: SessionStatus | undefined;
}

function createBaseSession(): Session {
  return { Id: "", ownerId: "", participants: [], createdAt: "", updatedAt: "", endedAt: "", status: "", language: "" };
}

export const Session: MessageFns<Session> = {
  encode(message: Session, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.Id !== "") {
      writer.uint32(10).string(message.Id);
    }
    if (message.ownerId !== "") {
      writer.uint32(26).string(message.ownerId);
    }
    for (const v of message.participants) {
      writer.uint32(34).string(v!);
    }
    if (message.createdAt !== "") {
      writer.uint32(42).string(message.createdAt);
    }
    if (message.updatedAt !== "") {
      writer.uint32(50).string(message.updatedAt);
    }
    if (message.endedAt !== "") {
      writer.uint32(58).string(message.endedAt);
    }
    if (message.status !== "") {
      writer.uint32(66).string(message.status);
    }
    if (message.language !== "") {
      writer.uint32(74).string(message.language);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Session {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSession();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.Id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.ownerId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.participants.push(reader.string());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.updatedAt = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.endedAt = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.language = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Session {
    return {
      Id: isSet(object.Id) ? globalThis.String(object.Id) : "",
      ownerId: isSet(object.ownerId) ? globalThis.String(object.ownerId) : "",
      participants: globalThis.Array.isArray(object?.participants)
        ? object.participants.map((e: any) => globalThis.String(e))
        : [],
      createdAt: isSet(object.createdAt) ? globalThis.String(object.createdAt) : "",
      updatedAt: isSet(object.updatedAt) ? globalThis.String(object.updatedAt) : "",
      endedAt: isSet(object.endedAt) ? globalThis.String(object.endedAt) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      language: isSet(object.language) ? globalThis.String(object.language) : "",
    };
  },

  toJSON(message: Session): unknown {
    const obj: any = {};
    if (message.Id !== "") {
      obj.Id = message.Id;
    }
    if (message.ownerId !== "") {
      obj.ownerId = message.ownerId;
    }
    if (message.participants?.length) {
      obj.participants = message.participants;
    }
    if (message.createdAt !== "") {
      obj.createdAt = message.createdAt;
    }
    if (message.updatedAt !== "") {
      obj.updatedAt = message.updatedAt;
    }
    if (message.endedAt !== "") {
      obj.endedAt = message.endedAt;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.language !== "") {
      obj.language = message.language;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Session>, I>>(base?: I): Session {
    return Session.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Session>, I>>(object: I): Session {
    const message = createBaseSession();
    message.Id = object.Id ?? "";
    message.ownerId = object.ownerId ?? "";
    message.participants = object.participants?.map((e) => e) || [];
    message.createdAt = object.createdAt ?? "";
    message.updatedAt = object.updatedAt ?? "";
    message.endedAt = object.endedAt ?? "";
    message.status = object.status ?? "";
    message.language = object.language ?? "";
    return message;
  },
};

function createBaseCreateSessionRequest(): CreateSessionRequest {
  return { ownerId: "" };
}

export const CreateSessionRequest: MessageFns<CreateSessionRequest> = {
  encode(message: CreateSessionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ownerId !== "") {
      writer.uint32(10).string(message.ownerId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateSessionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateSessionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ownerId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateSessionRequest {
    return { ownerId: isSet(object.ownerId) ? globalThis.String(object.ownerId) : "" };
  },

  toJSON(message: CreateSessionRequest): unknown {
    const obj: any = {};
    if (message.ownerId !== "") {
      obj.ownerId = message.ownerId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateSessionRequest>, I>>(base?: I): CreateSessionRequest {
    return CreateSessionRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateSessionRequest>, I>>(object: I): CreateSessionRequest {
    const message = createBaseCreateSessionRequest();
    message.ownerId = object.ownerId ?? "";
    return message;
  },
};

function createBaseCreateSessionResponse(): CreateSessionResponse {
  return { inviteToken: "" };
}

export const CreateSessionResponse: MessageFns<CreateSessionResponse> = {
  encode(message: CreateSessionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.inviteToken !== "") {
      writer.uint32(10).string(message.inviteToken);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateSessionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateSessionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.inviteToken = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateSessionResponse {
    return { inviteToken: isSet(object.inviteToken) ? globalThis.String(object.inviteToken) : "" };
  },

  toJSON(message: CreateSessionResponse): unknown {
    const obj: any = {};
    if (message.inviteToken !== "") {
      obj.inviteToken = message.inviteToken;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateSessionResponse>, I>>(base?: I): CreateSessionResponse {
    return CreateSessionResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateSessionResponse>, I>>(object: I): CreateSessionResponse {
    const message = createBaseCreateSessionResponse();
    message.inviteToken = object.inviteToken ?? "";
    return message;
  },
};

function createBaseSessionStatus(): SessionStatus {
  return { active: 0, ended: 0, offline: 0 };
}

export const SessionStatus: MessageFns<SessionStatus> = {
  encode(message: SessionStatus, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.active !== 0) {
      writer.uint32(8).int32(message.active);
    }
    if (message.ended !== 0) {
      writer.uint32(16).int32(message.ended);
    }
    if (message.offline !== 0) {
      writer.uint32(24).int32(message.offline);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SessionStatus {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSessionStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.active = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.ended = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.offline = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SessionStatus {
    return {
      active: isSet(object.active) ? globalThis.Number(object.active) : 0,
      ended: isSet(object.ended) ? globalThis.Number(object.ended) : 0,
      offline: isSet(object.offline) ? globalThis.Number(object.offline) : 0,
    };
  },

  toJSON(message: SessionStatus): unknown {
    const obj: any = {};
    if (message.active !== 0) {
      obj.active = Math.round(message.active);
    }
    if (message.ended !== 0) {
      obj.ended = Math.round(message.ended);
    }
    if (message.offline !== 0) {
      obj.offline = Math.round(message.offline);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SessionStatus>, I>>(base?: I): SessionStatus {
    return SessionStatus.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SessionStatus>, I>>(object: I): SessionStatus {
    const message = createBaseSessionStatus();
    message.active = object.active ?? 0;
    message.ended = object.ended ?? 0;
    message.offline = object.offline ?? 0;
    return message;
  },
};

function createBaseGetSessionStatsResponse(): GetSessionStatsResponse {
  return { total: undefined, today: undefined };
}

export const GetSessionStatsResponse: MessageFns<GetSessionStatsResponse> = {
  encode(message: GetSessionStatsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.total !== undefined) {
      SessionStatus.encode(message.total, writer.uint32(10).fork()).join();
    }
    if (message.today !== undefined) {
      SessionStatus.encode(message.today, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetSessionStatsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetSessionStatsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.total = SessionStatus.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.today = SessionStatus.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetSessionStatsResponse {
    return {
      total: isSet(object.total) ? SessionStatus.fromJSON(object.total) : undefined,
      today: isSet(object.today) ? SessionStatus.fromJSON(object.today) : undefined,
    };
  },

  toJSON(message: GetSessionStatsResponse): unknown {
    const obj: any = {};
    if (message.total !== undefined) {
      obj.total = SessionStatus.toJSON(message.total);
    }
    if (message.today !== undefined) {
      obj.today = SessionStatus.toJSON(message.today);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetSessionStatsResponse>, I>>(base?: I): GetSessionStatsResponse {
    return GetSessionStatsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetSessionStatsResponse>, I>>(object: I): GetSessionStatsResponse {
    const message = createBaseGetSessionStatsResponse();
    message.total = (object.total !== undefined && object.total !== null)
      ? SessionStatus.fromPartial(object.total)
      : undefined;
    message.today = (object.today !== undefined && object.today !== null)
      ? SessionStatus.fromPartial(object.today)
      : undefined;
    return message;
  },
};

export type SessionManagerService = typeof SessionManagerService;
export const SessionManagerService = {
  createSession: {
    path: "/collab.v1.SessionManager/CreateSession",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: CreateSessionRequest): Buffer => Buffer.from(CreateSessionRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateSessionRequest => CreateSessionRequest.decode(value),
    responseSerialize: (value: CreateSessionResponse): Buffer =>
      Buffer.from(CreateSessionResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CreateSessionResponse => CreateSessionResponse.decode(value),
  },
  getSessionStats: {
    path: "/collab.v1.SessionManager/GetSessionStats",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: Empty): Buffer => Buffer.from(Empty.encode(value).finish()),
    requestDeserialize: (value: Buffer): Empty => Empty.decode(value),
    responseSerialize: (value: GetSessionStatsResponse): Buffer =>
      Buffer.from(GetSessionStatsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetSessionStatsResponse => GetSessionStatsResponse.decode(value),
  },
} as const;

export interface SessionManagerServer extends UntypedServiceImplementation {
  createSession: handleUnaryCall<CreateSessionRequest, CreateSessionResponse>;
  getSessionStats: handleUnaryCall<Empty, GetSessionStatsResponse>;
}

export interface SessionManagerClient extends Client {
  createSession(
    request: CreateSessionRequest,
    callback: (error: ServiceError | null, response: CreateSessionResponse) => void,
  ): ClientUnaryCall;
  createSession(
    request: CreateSessionRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CreateSessionResponse) => void,
  ): ClientUnaryCall;
  createSession(
    request: CreateSessionRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CreateSessionResponse) => void,
  ): ClientUnaryCall;
  getSessionStats(
    request: Empty,
    callback: (error: ServiceError | null, response: GetSessionStatsResponse) => void,
  ): ClientUnaryCall;
  getSessionStats(
    request: Empty,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetSessionStatsResponse) => void,
  ): ClientUnaryCall;
  getSessionStats(
    request: Empty,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetSessionStatsResponse) => void,
  ): ClientUnaryCall;
}

export const SessionManagerClient = makeGenericClientConstructor(
  SessionManagerService,
  "collab.v1.SessionManager",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): SessionManagerClient;
  service: typeof SessionManagerService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
